name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests (default features)
      run: cargo test --verbose --all-targets
    - name: Run tests (all features)
      run: cargo test --verbose --all-targets --all-features
    - name: Generate docs (default features)
      run: cargo doc --verbose
    - name: Generate docs (all features)
      run: cargo doc --verbose --all-features
